apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dl-api-deployment
spec:
  selector:
    matchLabels:
      app: flask-dl-api
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-dl-api
    spec:
     containers:
     - name: flask-dl-api
       image: mamieuu/flask-dl-api:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8080